auditbeat.modules:
  - module: auditd
    enabled: true

  - module: file_integrity
    paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc

  - module: system
    datasets:
      - user
      - login
      - process
      - socket
    period: 10s

output.logstash:
  hosts: ["${LOGSTASH_HOST}"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
